# Application configuration for NoyBlog
# Database connection settings
spring:
  application:
    name: noyblog
  datasource:
    url: jdbc:postgresql://192.168.1.100:5432/blogdb
    username: grummans
    password: WGEM1bUYD8nKMUd4
  banner:
    location: classpath:banner.txt

server:
  port: 8085
