# Application configuration for NoyBlog
# Database connection settings
spring:
  application:
    name: noyblog
  datasource:
    url: jdbc:postgresql://100.64.0.1:5432/blogdb?currentSchema=blogdb
    username: grummans
    password: WGEM1bUYD8nKMUd4
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  banner:
    location: classpath:banner.txt
server:
  port: 8085
  servlet:
    context-path: /api

# MinIO configuration
minio:
  accessKey: grummans
  secretKey: qLxNdEWJHiMBSSlh
  bucketName: grummans-bucket
  endpoint: https://minio.grummans.me

