# Application configuration for NoyBlog - Local Development
spring:
  datasource:
    url: ${DB_LOCAL_URL}
    username: ${DB_LOCAL_USERNAME}
    password: ${DB_LOCAL_PASSWORD}
    hikari:
      schema: ${DB_LOCAL_SCHEMA}

# MinIO configuration
minio:
  accessKey: ${MINIO_ACCESS_KEY:minio}
  secretKey: ${MINIO_SECRET_KEY:minio123}
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}

server:
  port: 8085
  servlet:
    context-path: /api